global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:5000"]

  # Add this to fix Network/CPU "No Data"
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]